"""Initial migration

Revision ID: eda8e1f446f7
Revises: 
Create Date: 2024-03-02 15:41:16.946259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eda8e1f446f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('average_data', schema=None) as batch_op:
        batch_op.alter_column('average',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.alter_column('hair_state',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('subtitle',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('author',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('date_posted',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('slug',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.BLOB(), nullable=False))
        batch_op.alter_column('slug',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=True)
        batch_op.alter_column('date_posted',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=True)
        batch_op.alter_column('subtitle',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=True)

    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.alter_column('hair_state',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('average_data', schema=None) as batch_op:
        batch_op.alter_column('average',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
